"""Map a human-readable location (country, continent, or major city) to an
IANA timezone.

The model passes a single ``location`` string to :func:`resolve` and the
backend figures out the actual zone. This keeps the tool schema in the
system prompt tiny (no 600-value enum) while still giving the model
broad freedom to say "Japan", "Asia", "Tokyo", "USA", etc.

Data is curated: every UN member state (mapped to its capital's zone),
all major world cities, the seven continents, and the most common
short-form aliases ("UK", "USA", "UAE", "NZ", ...). The :func:`resolve`
function is permissive — it lowercases, normalises punctuation, and
falls back to fuzzy matching for typos.
"""

from difflib import get_close_matches
from typing import Final

# All keys are lowercased; values are IANA timezone names from ``zoneinfo``.
# The mapping is built from a curated list: every UN member state (mapped to
# the timezone of its capital), major world cities, the seven continents,
# and a handful of common short-form aliases. Add more entries as needed.
_TIMEZONE_MAP: Final[dict[str, str]] = {
    # ------------------------------------------------------------------
    # Continents — each maps to a representative zone (continent-level
    # queries are inherently ambiguous; the model can be more specific
    # by passing a country or city).
    # ------------------------------------------------------------------
    "africa": "Africa/Cairo",
    "asia": "Asia/Singapore",
    "europe": "Europe/London",
    "america": "America/New_York",
    "americas": "America/New_York",
    "north america": "America/New_York",
    "south america": "America/Sao_Paulo",
    "oceania": "Australia/Sydney",
    "antarctica": "Antarctica/McMurdo",
    "pacific": "Pacific/Auckland",
    # ------------------------------------------------------------------
    # Countries — UN member states, mapped to the timezone of their
    # capital (or the most-populous zone where capitals span zones).
    # ------------------------------------------------------------------
    # Africa
    "algeria": "Africa/Algiers",
    "angola": "Africa/Luanda",
    "benin": "Africa/Porto-Novo",
    "botswana": "Africa/Gaborone",
    "burkina faso": "Africa/Ouagadougou",
    "burundi": "Africa/Bujumbura",
    "cabo verde": "Atlantic/Cape_Verde",
    "cape verde": "Atlantic/Cape_Verde",
    "cameroon": "Africa/Douala",
    "central african republic": "Africa/Bangui",
    "chad": "Africa/Ndjamena",
    "comoros": "Indian/Comoro",
    "congo": "Africa/Brazzaville",
    "democratic republic of the congo": "Africa/Kinshasa",
    "drc": "Africa/Kinshasa",
    "djibouti": "Africa/Djibouti",
    "egypt": "Africa/Cairo",
    "equatorial guinea": "Africa/Malabo",
    "eritrea": "Africa/Asmera",
    "eswatini": "Africa/Mbabane",
    "swaziland": "Africa/Mbabane",
    "ethiopia": "Africa/Addis_Ababa",
    "gabon": "Africa/Libreville",
    "gambia": "Africa/Banjul",
    "ghana": "Africa/Accra",
    "guinea": "Africa/Conakry",
    "guinea-bissau": "Africa/Bissau",
    "ivory coast": "Africa/Abidjan",
    "cote d'ivoire": "Africa/Abidjan",
    "kenya": "Africa/Nairobi",
    "lesotho": "Africa/Maseru",
    "liberia": "Africa/Monrovia",
    "libya": "Africa/Tripoli",
    "madagascar": "Indian/Antananarivo",
    "malawi": "Africa/Blantyre",
    "mali": "Africa/Bamako",
    "mauritania": "Africa/Nouakchott",
    "mauritius": "Indian/Mauritius",
    "morocco": "Africa/Casablanca",
    "mozambique": "Africa/Maputo",
    "namibia": "Africa/Windhoek",
    "niger": "Africa/Niamey",
    "nigeria": "Africa/Lagos",
    "rwanda": "Africa/Kigali",
    "sao tome and principe": "Africa/Sao_Tome",
    "senegal": "Africa/Dakar",
    "seychelles": "Indian/Mahe",
    "sierra leone": "Africa/Freetown",
    "somalia": "Africa/Mogadishu",
    "south africa": "Africa/Johannesburg",
    "south sudan": "Africa/Juba",
    "sudan": "Africa/Khartoum",
    "tanzania": "Africa/Dar_es_Salaam",
    "togo": "Africa/Lome",
    "tunisia": "Africa/Tunis",
    "uganda": "Africa/Kampala",
    "zambia": "Africa/Lusaka",
    "zimbabwe": "Africa/Harare",
    # Americas
    "antigua and barbuda": "America/Antigua",
    "argentina": "America/Argentina/Buenos_Aires",
    "bahamas": "America/Nassau",
    "barbados": "America/Barbados",
    "belize": "America/Belize",
    "bolivia": "America/La_Paz",
    "brazil": "America/Sao_Paulo",
    "canada": "America/Toronto",
    "chile": "America/Santiago",
    "colombia": "America/Bogota",
    "costa rica": "America/Costa_Rica",
    "cuba": "America/Havana",
    "dominica": "America/Dominica",
    "dominican republic": "America/Santo_Domingo",
    "ecuador": "America/Guayaquil",
    "el salvador": "America/El_Salvador",
    "grenada": "America/Grenada",
    "guatemala": "America/Guatemala",
    "guyana": "America/Guyana",
    "haiti": "America/Port-au-Prince",
    "honduras": "America/Tegucigalpa",
    "jamaica": "America/Jamaica",
    "mexico": "America/Mexico_City",
    "nicaragua": "America/Managua",
    "panama": "America/Panama",
    "paraguay": "America/Asuncion",
    "peru": "America/Lima",
    "saint kitts and nevis": "America/St_Kitts",
    "saint lucia": "America/St_Lucia",
    "saint vincent and the grenadines": "America/St_Vincent",
    "suriname": "America/Paramaribo",
    "trinidad and tobago": "America/Port_of_Spain",
    "united states": "America/New_York",
    "united states of america": "America/New_York",
    "uruguay": "America/Montevideo",
    "venezuela": "America/Caracas",
    # Asia
    "afghanistan": "Asia/Kabul",
    "armenia": "Asia/Yerevan",
    "azerbaijan": "Asia/Baku",
    "bahrain": "Asia/Bahrain",
    "bangladesh": "Asia/Dhaka",
    "bhutan": "Asia/Thimphu",
    "brunei": "Asia/Brunei",
    "cambodia": "Asia/Phnom_Penh",
    "china": "Asia/Shanghai",
    "cyprus": "Asia/Nicosia",
    "georgia": "Asia/Tbilisi",
    "india": "Asia/Kolkata",
    "indonesia": "Asia/Jakarta",
    "iran": "Asia/Tehran",
    "iraq": "Asia/Baghdad",
    "israel": "Asia/Jerusalem",
    "japan": "Asia/Tokyo",
    "jordan": "Asia/Amman",
    "kazakhstan": "Asia/Almaty",
    "kuwait": "Asia/Kuwait",
    "kyrgyzstan": "Asia/Bishkek",
    "laos": "Asia/Vientiane",
    "lebanon": "Asia/Beirut",
    "malaysia": "Asia/Kuala_Lumpur",
    "maldives": "Indian/Maldives",
    "mongolia": "Asia/Ulaanbaatar",
    "myanmar": "Asia/Yangon",
    "burma": "Asia/Yangon",
    "nepal": "Asia/Kathmandu",
    "oman": "Asia/Muscat",
    "pakistan": "Asia/Karachi",
    "palestine": "Asia/Gaza",
    "philippines": "Asia/Manila",
    "qatar": "Asia/Qatar",
    "saudi arabia": "Asia/Riyadh",
    "singapore": "Asia/Singapore",
    "south korea": "Asia/Seoul",
    "korea": "Asia/Seoul",
    "sri lanka": "Asia/Colombo",
    "syria": "Asia/Damascus",
    "taiwan": "Asia/Taipei",
    "tajikistan": "Asia/Dushanbe",
    "thailand": "Asia/Bangkok",
    "timor-leste": "Asia/Dili",
    "east timor": "Asia/Dili",
    "turkey": "Europe/Istanbul",
    "turkmenistan": "Asia/Ashgabat",
    "united arab emirates": "Asia/Dubai",
    "uzbekistan": "Asia/Tashkent",
    "vietnam": "Asia/Ho_Chi_Minh",
    "yemen": "Asia/Aden",
    # Europe
    "albania": "Europe/Tirane",
    "andorra": "Europe/Andorra",
    "austria": "Europe/Vienna",
    "belarus": "Europe/Minsk",
    "belgium": "Europe/Brussels",
    "bosnia and herzegovina": "Europe/Sarajevo",
    "bulgaria": "Europe/Sofia",
    "croatia": "Europe/Zagreb",
    "czechia": "Europe/Prague",
    "czech republic": "Europe/Prague",
    "denmark": "Europe/Copenhagen",
    "estonia": "Europe/Tallinn",
    "finland": "Europe/Helsinki",
    "france": "Europe/Paris",
    "germany": "Europe/Berlin",
    "greece": "Europe/Athens",
    "hungary": "Europe/Budapest",
    "iceland": "Atlantic/Reykjavik",
    "ireland": "Europe/Dublin",
    "italy": "Europe/Rome",
    "kosovo": "Europe/Belgrade",
    "latvia": "Europe/Riga",
    "liechtenstein": "Europe/Vaduz",
    "lithuania": "Europe/Vilnius",
    "luxembourg": "Europe/Luxembourg",
    "malta": "Europe/Malta",
    "moldova": "Europe/Chisinau",
    "monaco": "Europe/Monaco",
    "montenegro": "Europe/Podgorica",
    "netherlands": "Europe/Amsterdam",
    "north macedonia": "Europe/Skopje",
    "norway": "Europe/Oslo",
    "poland": "Europe/Warsaw",
    "portugal": "Europe/Lisbon",
    "romania": "Europe/Bucharest",
    "russia": "Europe/Moscow",
    "san marino": "Europe/San_Marino",
    "serbia": "Europe/Belgrade",
    "slovakia": "Europe/Bratislava",
    "slovenia": "Europe/Ljubljana",
    "spain": "Europe/Madrid",
    "sweden": "Europe/Stockholm",
    "switzerland": "Europe/Zurich",
    "ukraine": "Europe/Kiev",
    "united kingdom": "Europe/London",
    "great britain": "Europe/London",
    "vatican": "Europe/Vatican",
    "vatican city": "Europe/Vatican",
    # Oceania
    "australia": "Australia/Sydney",
    "fiji": "Pacific/Fiji",
    "kiribati": "Pacific/Tarawa",
    "marshall islands": "Pacific/Majuro",
    "micronesia": "Pacific/Pohnpei",
    "nauru": "Pacific/Nauru",
    "new zealand": "Pacific/Auckland",
    "palau": "Pacific/Palau",
    "papua new guinea": "Pacific/Port_Moresby",
    "samoa": "Pacific/Apia",
    "solomon islands": "Pacific/Guadalcanal",
    "tonga": "Pacific/Tongatapu",
    "tuvalu": "Pacific/Funafuti",
    "vanuatu": "Pacific/Efate",
    # ------------------------------------------------------------------
    # US states — each maps to the timezone of its capital (or the
    # most-populous zone where a state spans multiple, e.g. Florida →
    # Eastern). The model can pass a state name ("Maryland") or a city
    # name ("Baltimore") and get the same answer.
    # ------------------------------------------------------------------
    "alabama": "America/Chicago",
    "alaska": "America/Anchorage",
    "arizona": "America/Phoenix",
    "arkansas": "America/Chicago",
    "california": "America/Los_Angeles",
    "colorado": "America/Denver",
    "connecticut": "America/New_York",
    "delaware": "America/New_York",
    "florida": "America/New_York",
    "hawaii": "Pacific/Honolulu",
    "idaho": "America/Boise",
    "illinois": "America/Chicago",
    "indiana": "America/Indiana/Indianapolis",
    "iowa": "America/Chicago",
    "kansas": "America/Chicago",
    "kentucky": "America/New_York",
    "louisiana": "America/Chicago",
    "maine": "America/New_York",
    "maryland": "America/New_York",
    "massachusetts": "America/New_York",
    "michigan": "America/New_York",
    "minnesota": "America/Chicago",
    "mississippi": "America/Chicago",
    "missouri": "America/Chicago",
    "montana": "America/Denver",
    "nebraska": "America/Chicago",
    "nevada": "America/Los_Angeles",
    "new hampshire": "America/New_York",
    "new jersey": "America/New_York",
    "new mexico": "America/Denver",
    "new york state": "America/New_York",
    "north carolina": "America/New_York",
    "north dakota": "America/Chicago",
    "ohio": "America/New_York",
    "oklahoma": "America/Chicago",
    "oregon": "America/Los_Angeles",
    "pennsylvania": "America/New_York",
    "rhode island": "America/New_York",
    "south carolina": "America/New_York",
    "south dakota": "America/Chicago",
    "tennessee": "America/New_York",
    "texas": "America/Chicago",
    "utah": "America/Denver",
    "vermont": "America/New_York",
    "virginia": "America/New_York",
    # "washington" intentionally skipped — see the city entry below
    # which maps to Washington DC (Eastern). Pass "washington state"
    # for the Pacific zone, or any WA city (Seattle, Tacoma, ...).
    "washington state": "America/Los_Angeles",
    "west virginia": "America/New_York",
    "wisconsin": "America/Chicago",
    "wyoming": "America/Denver",
    # ------------------------------------------------------------------
    # Major cities — top world cities and well-known regional capitals.
    # Multiple cities in the same country map to the same zone, so the
    # model can pass either "Japan" or "Tokyo" and get the same answer.
    # ------------------------------------------------------------------
    # Asia
    "tokyo": "Asia/Tokyo",
    "osaka": "Asia/Tokyo",
    "kyoto": "Asia/Tokyo",
    "nagoya": "Asia/Tokyo",
    "sapporo": "Asia/Tokyo",
    "fukuoka": "Asia/Tokyo",
    "yokohama": "Asia/Tokyo",
    "delhi": "Asia/Kolkata",
    "mumbai": "Asia/Kolkata",
    "bombay": "Asia/Kolkata",
    "kolkata": "Asia/Kolkata",
    "calcutta": "Asia/Kolkata",
    "bangalore": "Asia/Kolkata",
    "bengaluru": "Asia/Kolkata",
    "chennai": "Asia/Kolkata",
    "madras": "Asia/Kolkata",
    "hyderabad": "Asia/Kolkata",
    "ahmedabad": "Asia/Kolkata",
    "pune": "Asia/Kolkata",
    "beijing": "Asia/Shanghai",
    "shanghai": "Asia/Shanghai",
    "guangzhou": "Asia/Shanghai",
    "shenzhen": "Asia/Shanghai",
    "tianjin": "Asia/Shanghai",
    "chengdu": "Asia/Shanghai",
    "wuhan": "Asia/Shanghai",
    "hong kong": "Asia/Hong_Kong",
    "macau": "Asia/Macau",
    "taipei": "Asia/Taipei",
    "kaohsiung": "Asia/Taipei",
    "manila": "Asia/Manila",
    "quezon city": "Asia/Manila",
    "jakarta": "Asia/Jakarta",
    "surabaya": "Asia/Jakarta",
    "bandung": "Asia/Jakarta",
    "bangkok": "Asia/Bangkok",
    "chiang mai": "Asia/Bangkok",
    "phuket": "Asia/Bangkok",
    "hanoi": "Asia/Ho_Chi_Minh",
    "ho chi minh city": "Asia/Ho_Chi_Minh",
    "saigon": "Asia/Ho_Chi_Minh",
    "phnom penh": "Asia/Phnom_Penh",
    "vientiane": "Asia/Vientiane",
    "yangon": "Asia/Yangon",
    "rangoon": "Asia/Yangon",
    "kuala lumpur": "Asia/Kuala_Lumpur",
    "seoul": "Asia/Seoul",
    "busan": "Asia/Seoul",
    "incheon": "Asia/Seoul",
    "pyongyang": "Asia/Pyongyang",
    "ulaanbaatar": "Asia/Ulaanbaatar",
    "karachi": "Asia/Karachi",
    "lahore": "Asia/Karachi",
    "islamabad": "Asia/Karachi",
    "dhaka": "Asia/Dhaka",
    "chittagong": "Asia/Dhaka",
    "kabul": "Asia/Kabul",
    "tehran": "Asia/Tehran",
    "baghdad": "Asia/Baghdad",
    "riyadh": "Asia/Riyadh",
    "jeddah": "Asia/Riyadh",
    "mecca": "Asia/Riyadh",
    "medina": "Asia/Riyadh",
    "doha": "Asia/Qatar",
    "manama": "Asia/Bahrain",
    "kuwait city": "Asia/Kuwait",
    "muscat": "Asia/Muscat",
    "dubai": "Asia/Dubai",
    "abu dhabi": "Asia/Dubai",
    "sharjah": "Asia/Dubai",
    "amman": "Asia/Amman",
    "beirut": "Asia/Beirut",
    "damascus": "Asia/Damascus",
    "jerusalem": "Asia/Jerusalem",
    "tel aviv": "Asia/Jerusalem",
    "baku": "Asia/Baku",
    "yerevan": "Asia/Yerevan",
    "tbilisi": "Asia/Tbilisi",
    "almaty": "Asia/Almaty",
    "tashkent": "Asia/Tashkent",
    "bishkek": "Asia/Bishkek",
    "dushanbe": "Asia/Dushanbe",
    "ashgabat": "Asia/Ashgabat",
    "kathmandu": "Asia/Kathmandu",
    "colombo": "Asia/Colombo",
    "male": "Indian/Maldives",
    "thimphu": "Asia/Thimphu",
    # Middle East
    "istanbul": "Europe/Istanbul",
    "ankara": "Europe/Istanbul",
    "izmir": "Europe/Istanbul",
    # Europe
    "london": "Europe/London",
    "manchester": "Europe/London",
    "birmingham": "Europe/London",
    "edinburgh": "Europe/London",
    "glasgow": "Europe/London",
    "dublin": "Europe/Dublin",
    "cork": "Europe/Dublin",
    "paris": "Europe/Paris",
    "lyon": "Europe/Paris",
    "marseille": "Europe/Paris",
    "berlin": "Europe/Berlin",
    "munich": "Europe/Berlin",
    "frankfurt": "Europe/Berlin",
    "hamburg": "Europe/Berlin",
    "cologne": "Europe/Berlin",
    "stuttgart": "Europe/Berlin",
    "dusseldorf": "Europe/Berlin",
    "rome": "Europe/Rome",
    "milan": "Europe/Rome",
    "naples": "Europe/Rome",
    "florence": "Europe/Rome",
    "venice": "Europe/Rome",
    "madrid": "Europe/Madrid",
    "barcelona": "Europe/Madrid",
    "valencia": "Europe/Madrid",
    "seville": "Europe/Madrid",
    "lisbon": "Europe/Lisbon",
    "porto": "Europe/Lisbon",
    "amsterdam": "Europe/Amsterdam",
    "rotterdam": "Europe/Amsterdam",
    "brussels": "Europe/Brussels",
    "antwerp": "Europe/Brussels",
    "vienna": "Europe/Vienna",
    "salzburg": "Europe/Vienna",
    "zurich": "Europe/Zurich",
    "geneva": "Europe/Zurich",
    "bern": "Europe/Zurich",
    "stockholm": "Europe/Stockholm",
    "gothenburg": "Europe/Stockholm",
    "oslo": "Europe/Oslo",
    "bergen": "Europe/Oslo",
    "copenhagen": "Europe/Copenhagen",
    "helsinki": "Europe/Helsinki",
    "reykjavik": "Atlantic/Reykjavik",
    "warsaw": "Europe/Warsaw",
    "krakow": "Europe/Warsaw",
    "prague": "Europe/Prague",
    "budapest": "Europe/Budapest",
    "bucharest": "Europe/Bucharest",
    "sofia": "Europe/Sofia",
    "belgrade": "Europe/Belgrade",
    "zagreb": "Europe/Zagreb",
    "ljubljana": "Europe/Ljubljana",
    "sarajevo": "Europe/Sarajevo",
    "skopje": "Europe/Skopje",
    "tirana": "Europe/Tirane",
    "athens": "Europe/Athens",
    "thessaloniki": "Europe/Athens",
    "valletta": "Europe/Malta",
    "bratislava": "Europe/Bratislava",
    "vilnius": "Europe/Vilnius",
    "riga": "Europe/Riga",
    "tallinn": "Europe/Tallinn",
    "minsk": "Europe/Minsk",
    "kiev": "Europe/Kiev",
    "kyiv": "Europe/Kiev",
    "chisinau": "Europe/Chisinau",
    "moscow": "Europe/Moscow",
    "saint petersburg": "Europe/Moscow",
    "st petersburg": "Europe/Moscow",
    "vaduz": "Europe/Vaduz",
    "andorra la vella": "Europe/Andorra",
    # Africa
    "cairo": "Africa/Cairo",
    "alexandria": "Africa/Cairo",
    "lagos": "Africa/Lagos",
    "abuja": "Africa/Lagos",
    "kinshasa": "Africa/Kinshasa",
    "luanda": "Africa/Luanda",
    "dar es salaam": "Africa/Dar_es_Salaam",
    "nairobi": "Africa/Nairobi",
    "addis ababa": "Africa/Addis_Ababa",
    "khartoum": "Africa/Khartoum",
    "juba": "Africa/Juba",
    "kampala": "Africa/Kampala",
    "kigali": "Africa/Kigali",
    "mogadishu": "Africa/Mogadishu",
    "dakar": "Africa/Dakar",
    "accra": "Africa/Accra",
    "abidjan": "Africa/Abidjan",
    "bamako": "Africa/Bamako",
    "ouagadougou": "Africa/Ouagadougou",
    "niamey": "Africa/Niamey",
    "lome": "Africa/Lome",
    "cotonou": "Africa/Porto-Novo",
    "porto-novo": "Africa/Porto-Novo",
    "yaounde": "Africa/Douala",
    "douala": "Africa/Douala",
    "libreville": "Africa/Libreville",
    "malabo": "Africa/Malabo",
    "bangui": "Africa/Bangui",
    "ndjamena": "Africa/Ndjamena",
    "brazzaville": "Africa/Brazzaville",
    "windhoek": "Africa/Windhoek",
    "gaborone": "Africa/Gaborone",
    "harare": "Africa/Harare",
    "lusaka": "Africa/Lusaka",
    "lilongwe": "Africa/Blantyre",
    "maputo": "Africa/Maputo",
    "mbabane": "Africa/Mbabane",
    "maseru": "Africa/Maseru",
    "antananarivo": "Indian/Antananarivo",
    "moroni": "Indian/Comoro",
    "victoria": "Indian/Mahe",
    "port louis": "Indian/Mauritius",
    "tripoli": "Africa/Tripoli",
    "tunis": "Africa/Tunis",
    "algiers": "Africa/Algiers",
    "rabat": "Africa/Casablanca",
    "casablanca": "Africa/Casablanca",
    "nouakchott": "Africa/Nouakchott",
    "banjul": "Africa/Banjul",
    "freetown": "Africa/Freetown",
    "monrovia": "Africa/Monrovia",
    "conakry": "Africa/Conakry",
    "bissau": "Africa/Bissau",
    "praia": "Atlantic/Cape_Verde",
    "johannesburg": "Africa/Johannesburg",
    "cape town": "Africa/Johannesburg",
    "durban": "Africa/Johannesburg",
    "pretoria": "Africa/Johannesburg",
    "asmara": "Africa/Asmera",
    "sao tome": "Africa/Sao_Tome",
    # Americas
    "new york": "America/New_York",
    "nyc": "America/New_York",
    "manhattan": "America/New_York",
    "brooklyn": "America/New_York",
    "boston": "America/New_York",
    "philadelphia": "America/New_York",
    "washington": "America/New_York",
    "dc": "America/New_York",
    "washington dc": "America/New_York",
    "baltimore": "America/New_York",
    "annapolis": "America/New_York",
    "atlanta": "America/New_York",
    "miami": "America/New_York",
    "orlando": "America/New_York",
    "tampa": "America/New_York",
    "jacksonville": "America/New_York",
    "charlotte": "America/New_York",
    "pittsburgh": "America/New_York",
    "detroit": "America/New_York",
    "toronto": "America/Toronto",
    "montreal": "America/Toronto",
    "ottawa": "America/Toronto",
    "quebec": "America/Toronto",
    "vancouver": "America/Vancouver",
    "calgary": "America/Edmonton",
    "edmonton": "America/Edmonton",
    "winnipeg": "America/Winnipeg",
    "halifax": "America/Halifax",
    "chicago": "America/Chicago",
    "houston": "America/Chicago",
    "dallas": "America/Chicago",
    "austin": "America/Chicago",
    "san antonio": "America/Chicago",
    "minneapolis": "America/Chicago",
    "new orleans": "America/Chicago",
    "memphis": "America/Chicago",
    "kansas city": "America/Chicago",
    "denver": "America/Denver",
    "salt lake city": "America/Denver",
    "phoenix": "America/Phoenix",
    "los angeles": "America/Los_Angeles",
    "la": "America/Los_Angeles",
    "san francisco": "America/Los_Angeles",
    "sf": "America/Los_Angeles",
    "san diego": "America/Los_Angeles",
    "seattle": "America/Los_Angeles",
    "portland": "America/Los_Angeles",
    "las vegas": "America/Los_Angeles",
    "honolulu": "Pacific/Honolulu",
    "anchorage": "America/Anchorage",
    "mexico city": "America/Mexico_City",
    "guadalajara": "America/Mexico_City",
    "monterrey": "America/Monterrey",
    "cancun": "America/Cancun",
    "tijuana": "America/Tijuana",
    "havana": "America/Havana",
    "kingston": "America/Jamaica",
    "nassau": "America/Nassau",
    "port-au-prince": "America/Port-au-Prince",
    "santo domingo": "America/Santo_Domingo",
    "san juan": "America/Puerto_Rico",
    "panama city": "America/Panama",
    "san jose": "America/Costa_Rica",
    "guatemala city": "America/Guatemala",
    "tegucigalpa": "America/Tegucigalpa",
    "managua": "America/Managua",
    "san salvador": "America/El_Salvador",
    "belmopan": "America/Belize",
    "quito": "America/Guayaquil",
    "guayaquil": "America/Guayaquil",
    "lima": "America/Lima",
    "la paz": "America/La_Paz",
    "santiago": "America/Santiago",
    "montevideo": "America/Montevideo",
    "asuncion": "America/Asuncion",
    "buenos aires": "America/Argentina/Buenos_Aires",
    "bogota": "America/Bogota",
    "caracas": "America/Caracas",
    "georgetown": "America/Guyana",
    "paramaribo": "America/Paramaribo",
    "cayenne": "America/Cayenne",
    "brasilia": "America/Sao_Paulo",
    "sao paulo": "America/Sao_Paulo",
    "rio de janeiro": "America/Sao_Paulo",
    "salvador": "America/Bahia",
    "fortaleza": "America/Fortaleza",
    "recife": "America/Recife",
    "manaus": "America/Manaus",
    "belem": "America/Belem",
    "curitiba": "America/Sao_Paulo",
    "porto alegre": "America/Sao_Paulo",
    "bridgetown": "America/Barbados",
    "roseau": "America/Dominica",
    "st george's": "America/Grenada",
    "basseterre": "America/St_Kitts",
    "castries": "America/St_Lucia",
    "kingstown": "America/St_Vincent",
    "port of spain": "America/Port_of_Spain",
    "antigua": "America/Antigua",
    # Oceania
    "sydney": "Australia/Sydney",
    "melbourne": "Australia/Melbourne",
    "brisbane": "Australia/Brisbane",
    "perth": "Australia/Perth",
    "adelaide": "Australia/Adelaide",
    "canberra": "Australia/Sydney",
    "hobart": "Australia/Hobart",
    "darwin": "Australia/Darwin",
    "auckland": "Pacific/Auckland",
    "wellington": "Pacific/Auckland",
    "christchurch": "Pacific/Auckland",
    "suva": "Pacific/Fiji",
    "apia": "Pacific/Apia",
    "nuku'alofa": "Pacific/Tongatapu",
    "port moresby": "Pacific/Port_Moresby",
    "honiara": "Pacific/Guadalcanal",
    "port vila": "Pacific/Efate",
    "tarawa": "Pacific/Tarawa",
    "majuro": "Pacific/Majuro",
    "pohnpei": "Pacific/Pohnpei",
    "palikir": "Pacific/Pohnpei",
    "yaren": "Pacific/Nauru",
    "ngerulmud": "Pacific/Palau",
    "funafuti": "Pacific/Funafuti",
    "mcmurdo": "Antarctica/McMurdo",
    # ------------------------------------------------------------------
    # Common short-form aliases — so the model can say "UK" instead of
    # "United Kingdom", "USA" instead of "United States", etc.
    # ------------------------------------------------------------------
    "usa": "America/New_York",
    "us": "America/New_York",
    "uk": "Europe/London",
    "britain": "Europe/London",
    "england": "Europe/London",
    "scotland": "Europe/London",
    "wales": "Europe/London",
    "northern ireland": "Europe/London",
    "uae": "Asia/Dubai",
    "emirates": "Asia/Dubai",
    "nz": "Pacific/Auckland",
    "aus": "Australia/Sydney",
    "au": "Australia/Sydney",
    "prc": "Asia/Shanghai",
    "mainland china": "Asia/Shanghai",
    "holland": "Europe/Amsterdam",
    "the netherlands": "Europe/Amsterdam",
    "czechoslovakia": "Europe/Prague",
}


def resolve(query: str) -> str:
    """Resolve a human-readable location to an IANA timezone.

    Accepts a country name (e.g. ``"Japan"``), continent (``"Asia"``),
    or major city (``"Tokyo"``), as well as common short-form aliases
    (``"UK"``, ``"USA"``). Returns the IANA timezone string for use
    with :class:`zoneinfo.ZoneInfo`.

    The empty string and the literal ``"local"`` both return
    ``"local"`` so the caller can use this as a single entry point for
    every input the model might send.

    Raises :class:`ValueError` with a helpful hint if no match is found.
    """
    if not query:
        return "local"
    key = query.lower().strip()
    if key == "local":
        return "local"

    # Exact match — fastest path
    if key in _TIMEZONE_MAP:
        return _TIMEZONE_MAP[key]

    # Tolerate underscores vs spaces (e.g. "New_York" -> "new york")
    if "_" in key:
        key_spaced = key.replace("_", " ")
        if key_spaced in _TIMEZONE_MAP:
            return _TIMEZONE_MAP[key_spaced]
    if " " in key:
        key_underscored = key.replace(" ", "_")
        if key_underscored in _TIMEZONE_MAP:
            return _TIMEZONE_MAP[key_underscored]

    # Strip common punctuation (apostrophes, hyphens) for a second pass
    key_clean = key.replace("'", "").replace("-", " ")
    if key_clean != key and key_clean in _TIMEZONE_MAP:
        return _TIMEZONE_MAP[key_clean]

    # Fuzzy match for typos. ``get_close_matches`` ranks candidates by
    # SequenceMatcher ratio, so common misspellings resolve to the
    # intended entry rather than failing outright.
    candidates = get_close_matches(key, _TIMEZONE_MAP.keys(), n=1, cutoff=0.8)
    if candidates:
        return _TIMEZONE_MAP[candidates[0]]

    raise ValueError(
        f"Unknown location: {query!r}. "
        "Pass a country (e.g. 'Japan'), continent (e.g. 'Asia'), "
        "or major city (e.g. 'Tokyo'). Use 'local' for the system clock."
    )
